llm:
  routing:
    rewrite: google_rewrite
    qa: google_qa
    summarize: google_summarize

  models:
    google_rewrite:
      provider: google
      model_name: gemma-3-4b-it

    google_qa:
      provider: google
      model_name: gemma-4-31b-it

    google_summarize:
      provider: google
      model_name: gemini-3.1-flash-lite-preview

embedding:
  model_name: gemini-embedding-2-preview